#!/bin/bash

trap 'chown -R --reference /build-scripts/build-package /out/' EXIT

if [ "$RELEASE" == 'precise' ] 
then 
    echo 'deb http://repo.pagely.com/debrepo/ondrej-php5-ubuntu/ precise main' >> /etc/apt/sources.list.d/pagely.list
fi

# condition check for 
apt-get -y update 
apt-get -y install php-pear \
                   ruby-dev \
                   gcc \
                   make 

apt-get -y --allow-unauthenticated install \
                   libsodium18 \
                   libsodium-dev


if [ "$RELEASE" == 'xenial' ] 
then 
    apt-get -y install php7.0 php7.0-dev 
else
    apt-get -y --allow-unauthenticated install php5 php5-dev 
fi

pecl install libsodium-${VERSION}
cd /out

EXT_DIR=$( php-config --extension-dir )

fpm -s dir -t deb \
    -n php-pecl-libsodium  \
    -v "${VERSION}-1${DISTRO}1~${RELEASE}1" \
    --description "libsodium PHP Pear module ${VERSION}" \
    --maintainer "anthony.dorfman@pagely.com" \
     --url "https://pecl.php.net/package/libsodium" \
    -a native \
    $EXT_DIR/libsodium.so

echo "$DISTRO $RELEASE $VERSION"


