#!/bin/bash

trap 'chown -R --reference /build-scripts/build-* /out/' EXIT

# condition check for 
apt-get -y update 
apt-get -y install \
     autoconf \
     binutils-doc \
     bison  \
     build-essential  \
     flex   \
     gettext  \
     ncurses-dev  \
     libxml2  \
     libxml2-dev \
     libxml2-utils  \
     libreadline-dev \
     libncurses5-dev \
     libpcre3-dev \
     libssl-dev  \
     perl  \
     libgeoip1 \
     geoip-bin \
     libgeoip-dev \
     wget \
     geoip-database


mkdir /build
mkdir /build/root

cd /build

wget https://openresty.org/download/openresty-${VERSION}.tar.gz
wget http://monitor.pagelydev.com/ngx_cache_purge-2.3.tar.gz
 
tar -xvzf openresty-${VERSION}.tar.gz
tar -xvzf ngx_cache_purge-2.3.tar.gz

cd openresty-${VERSION}

./configure \
  --with-luajit \
  --add-module=../ngx_cache_purge-2.3 \
  --with-http_realip_module \
  --with-http_stub_status_module \
  --with-http_ssl_module \
  --http-log-path=/mnt/log/nginx/access.log \
  --error-log-path=/mnt/log/nginx/error.log \
  --conf-path=/etc/nginx/nginx.conf \
  --lock-path=/var/lock/nginx.lock \
  --pid-path=/var/run/nginx.pid \
  --with-http_sub_module \
  --with-http_gunzip_module \
  --with-http_geoip_module \
  --with-http_v2_module

make -j 4

make install DESTDIR=/build/root

cd /out

# For precise FPM is under an RVM environemnt
/usr/local/rvm/bin/rvm_fpm -s dir -t deb \
    -n openresty  \
    -v "${VERSION}-1${DISTRO}1~${RELEASE}1" \
    -a native \
    -C /build/root \
    .
   
echo "$DISTRO $RELEASE $VERSION"


