#!/bin/bash

trap 'chown -R --reference /build-scripts/build-* /out/' EXIT

apt-get -y update 

apt-get -y install \
     autoconf \
     binutils-doc \
     bison  \
     build-essential  \
     flex   \
     gettext  \
     ncurses-dev  \
     libxml2  \
     libxml2-dev \
     libxml2-utils  \
     libreadline-dev \
     libncurses5-dev \
     libpcre3-dev \
     libssl-dev  \
     perl  \
     libgeoip1 \
     geoip-bin \
     libgeoip-dev \
     wget \
     geoip-database


mkdir /build
mkdir /build/root
mkdir /build/openssl

cd /build

wget https://openresty.org/download/openresty-${OR_VERSION}.tar.gz
wget http://monitor.pagelydev.com/ngx_cache_purge-2.3.tar.gz
wget https://www.openssl.org/source/openssl-1.0.2h.tar.gz
 
tar -xvzf openresty-${OR_VERSION}.tar.gz
tar -xvzf ngx_cache_purge-2.3.tar.gz
tar -xvzf openssl-1.0.2h.tar.gz

cd openresty-${OR_VERSION}

./configure \
  --with-luajit \
  --add-module=../ngx_cache_purge-2.3 \
  --with-openssl=/build/openssl-1.0.2h \
  --with-http_realip_module \
  --with-http_stub_status_module \
  --with-http_ssl_module \
  --http-log-path=/mnt/log/nginx/access.log \
  --error-log-path=/mnt/log/nginx/error.log \
  --conf-path=/etc/nginx/nginx.conf \
  --lock-path=/var/lock/nginx.lock \
  --pid-path=/var/run/nginx.pid \
  --with-http_sub_module \
  --with-http_gunzip_module \
  --with-http_geoip_module \
  --with-http_v2_module

make -j 4

make install DESTDIR=/build/root

cd /out

# For precise FPM is under an RVM environemnt
/usr/local/rvm/bin/rvm_fpm -s dir -t deb \
    -n openresty  \
    -v "${OR_VERSION}-1${DISTRO}1~${D_RELEASE}1" \
    --description "openresty ${NGINX_OR}" \
    -d libxslt1.1 \
    -d libgd2-xpm \
    -d libgeoip1 \
    -d libpcre3 \
    --conflicts nginx-extras \
    --conflicts nginx-full \
    --conflicts nginx-light \
    --config-files /etc/nginx/fastcgi.conf.default \
    --config-files /etc/nginx/win-utf \
    --config-files /etc/nginx/fastcgi_params \
    --config-files /etc/nginx/nginx.conf \
    --config-files /etc/nginx/koi-win \
    --config-files /etc/nginx/nginx.conf.default \
    --config-files /etc/nginx/mime.types.default  \
    --config-files /etc/nginx/koi-utf \
    --config-files /etc/nginx/fastcgi_params.default  \
    --config-files /etc/nginx/mime.types \
    --config-files /etc/nginx/fastcgi.conf \
    -a native \
    -C /build/root \
    .
   
echo "$DISTRO $D_RELEASE $OR_VERSION"


